#include "catch_amalgamated.hpp"
#include "../src/FigureFactories/RandomFigureFactory.h"

TEST_CASE("RandomFigureFactory generates valid figures and distribution is reasonable")
{
    const int N = 1000;
    RandomFigureFactory factory;

    int triangleLen = 8;
    int rectangleLen = 9;
    int circleLen = 6;

    int triangleCount = 0;
    int circleCount = 0;
    int rectangleCount = 0;

    for (int i = 0; i < N; ++i)
    {
        std::unique_ptr<Figure> fig = factory.create();
        std::string s = fig->to_string();

        if (s.substr(0, triangleLen) == "Triangle")
        {
            triangleCount++;

            std::stringstream ss(s.substr(triangleLen + 1));
            double a, b, c;
            ss >> a >> b >> c;

            REQUIRE(a >= 1);
            REQUIRE(a <= 2000);
            REQUIRE(b >= 1);
            REQUIRE(b <= 2000);
            REQUIRE(c >= 1);
            REQUIRE(c < a + b);
        }
        else if (s.substr(0, rectangleLen) == "Rectangle")
        {
            rectangleCount++;

            std::stringstream ss(s.substr(rectangleLen + 1));
            double a, b;
            ss >> a >> b;

            REQUIRE(a >= 1);
            REQUIRE(a <= 2000);
            REQUIRE(b >= 1);
            REQUIRE(b <= 2000);
        }
        else if (s.substr(0, circleLen) == "Circle")
        {
            circleCount++;

            std::stringstream ss(s.substr(circleLen + 1));
            double r;
            ss >> r;

            REQUIRE(r >= 1);
            REQUIRE(r <= 2000);
        }
        else
        {
            FAIL("Unknown figure generated by RandomFigureFactory");
        }
    }
    const double expected = N / 3.0;
    const double tolerance = expected * 0.20;
    REQUIRE(std::abs(triangleCount - expected) < tolerance);
    REQUIRE(std::abs(circleCount - expected) < tolerance);
    REQUIRE(std::abs(rectangleCount - expected) < tolerance);
}